<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260616101255 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajout des champs "événements de vie" sur user + tables payeur et abonnement.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE abonnement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_offre VARCHAR(64) NOT NULL, date_debut DATE NOT NULL, date_fin DATE DEFAULT NULL, statut VARCHAR(16) NOT NULL, montant NUMERIC(8, 2) NOT NULL, periodicite VARCHAR(16) NOT NULL, beneficiaire_id INT NOT NULL, payeur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_351268BB5AF81F68 ON abonnement (beneficiaire_id)');
        $this->addSql('CREATE INDEX IDX_351268BB422667C5 ON abonnement (payeur_id)');
        $this->addSql('CREATE TABLE payeur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prenom VARCHAR(100) NOT NULL, nom VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, lien_beneficiaire VARCHAR(32) NOT NULL, moyen_paiement VARCHAR(32) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE abonnement ADD CONSTRAINT FK_351268BB5AF81F68 FOREIGN KEY (beneficiaire_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE abonnement ADD CONSTRAINT FK_351268BB422667C5 FOREIGN KEY (payeur_id) REFERENCES payeur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD prenom VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD nom VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD date_naissance DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD situation VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD zone_geo VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD statut VARCHAR(16) DEFAULT \'actif\' NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD payeur_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649422667C5 FOREIGN KEY (payeur_id) REFERENCES payeur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_8D93D649422667C5 ON "user" (payeur_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE abonnement DROP CONSTRAINT FK_351268BB5AF81F68');
        $this->addSql('ALTER TABLE abonnement DROP CONSTRAINT FK_351268BB422667C5');
        $this->addSql('DROP TABLE abonnement');
        $this->addSql('DROP TABLE payeur');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649422667C5');
        $this->addSql('DROP INDEX IDX_8D93D649422667C5');
        $this->addSql('ALTER TABLE "user" DROP prenom');
        $this->addSql('ALTER TABLE "user" DROP nom');
        $this->addSql('ALTER TABLE "user" DROP date_naissance');
        $this->addSql('ALTER TABLE "user" DROP situation');
        $this->addSql('ALTER TABLE "user" DROP zone_geo');
        $this->addSql('ALTER TABLE "user" DROP statut');
        $this->addSql('ALTER TABLE "user" DROP payeur_id');
    }
}
