<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260617120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add forfait and payment tables for real notification triggers';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE forfait (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, label VARCHAR(80) NOT NULL, price NUMERIC(8, 2) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, renewal_notified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_forfait_user ON forfait (user_id)');
        $this->addSql('ALTER TABLE forfait ADD CONSTRAINT FK_forfait_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, forfait_id INT DEFAULT NULL, amount NUMERIC(8, 2) NOT NULL, status VARCHAR(16) NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, failure_notified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_payment_user ON payment (user_id)');
        $this->addSql('CREATE INDEX IDX_payment_forfait ON payment (forfait_id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_payment_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_payment_forfait FOREIGN KEY (forfait_id) REFERENCES forfait (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_payment_user');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_payment_forfait');
        $this->addSql('ALTER TABLE forfait DROP CONSTRAINT FK_forfait_user');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE forfait');
    }
}
