<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260616104000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add messaging tables for notifications, support conversations and line subscriptions';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE transit_line (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(32) NOT NULL, name VARCHAR(120) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_transit_line_code ON transit_line (code)');

        $this->addSql('CREATE TABLE line_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, line_id INT NOT NULL, enabled BOOLEAN NOT NULL, channels JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E8D2A1D0A76ED395 ON line_subscription (user_id)');
        $this->addSql('CREATE INDEX IDX_E8D2A1D071BAA4A1 ON line_subscription (line_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_line_subscription ON line_subscription (user_id, line_id)');
        $this->addSql('ALTER TABLE line_subscription ADD CONSTRAINT FK_E8D2A1D0A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE line_subscription ADD CONSTRAINT FK_E8D2A1D071BAA4A1 FOREIGN KEY (line_id) REFERENCES transit_line (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE user_notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, line_id INT DEFAULT NULL, title VARCHAR(160) NOT NULL, body TEXT NOT NULL, category VARCHAR(32) NOT NULL, priority VARCHAR(16) NOT NULL, is_read BOOLEAN NOT NULL, action_label VARCHAR(120) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8D93D649A76ED395 ON user_notification (user_id)');
        $this->addSql('CREATE INDEX IDX_8D93D64971BAA4A1 ON user_notification (line_id)');
        $this->addSql('ALTER TABLE user_notification ADD CONSTRAINT FK_8D93D649A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_notification ADD CONSTRAINT FK_8D93D64971BAA4A1 FOREIGN KEY (line_id) REFERENCES transit_line (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE support_conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, subject VARCHAR(180) NOT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C7A0A3A5A76ED395 ON support_conversation (user_id)');
        $this->addSql('ALTER TABLE support_conversation ADD CONSTRAINT FK_C7A0A3A5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE support_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, conversation_id INT NOT NULL, author VARCHAR(32) NOT NULL, content TEXT NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D175CD9598D2C56A ON support_message (conversation_id)');
        $this->addSql('ALTER TABLE support_message ADD CONSTRAINT FK_D175CD9598D2C56A FOREIGN KEY (conversation_id) REFERENCES support_conversation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE line_subscription DROP CONSTRAINT FK_E8D2A1D0A76ED395');
        $this->addSql('ALTER TABLE line_subscription DROP CONSTRAINT FK_E8D2A1D071BAA4A1');
        $this->addSql('ALTER TABLE user_notification DROP CONSTRAINT FK_8D93D649A76ED395');
        $this->addSql('ALTER TABLE user_notification DROP CONSTRAINT FK_8D93D64971BAA4A1');
        $this->addSql('ALTER TABLE support_conversation DROP CONSTRAINT FK_C7A0A3A5A76ED395');
        $this->addSql('ALTER TABLE support_message DROP CONSTRAINT FK_D175CD9598D2C56A');
        $this->addSql('DROP TABLE line_subscription');
        $this->addSql('DROP TABLE user_notification');
        $this->addSql('DROP TABLE support_message');
        $this->addSql('DROP TABLE support_conversation');
        $this->addSql('DROP TABLE transit_line');
    }
}
