<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260616105223 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Arbre de décision de l\'orientation : event_scenario, question, answer, recommendation.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE answer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, libelle VARCHAR(255) NOT NULL, ordre INT DEFAULT 0 NOT NULL, question_id INT NOT NULL, question_suivante_id INT DEFAULT NULL, recommendation_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DADD4A251E27F6BF ON answer (question_id)');
        $this->addSql('CREATE INDEX IDX_DADD4A25E349CFC0 ON answer (question_suivante_id)');
        $this->addSql('CREATE INDEX IDX_DADD4A25D173940B ON answer (recommendation_id)');
        $this->addSql('CREATE TABLE event_scenario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, label VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, icone VARCHAR(64) DEFAULT NULL, ordre INT DEFAULT 0 NOT NULL, question_initiale_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_78A92108A0520E1C ON event_scenario (question_initiale_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SCENARIO_CODE ON event_scenario (code)');
        $this->addSql('CREATE TABLE question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, libelle TEXT NOT NULL, type VARCHAR(16) NOT NULL, ordre INT DEFAULT 0 NOT NULL, scenario_id INT NOT NULL, question_suivante_id INT DEFAULT NULL, recommendation_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6F7494EE04E49DF ON question (scenario_id)');
        $this->addSql('CREATE INDEX IDX_B6F7494EE349CFC0 ON question (question_suivante_id)');
        $this->addSql('CREATE INDEX IDX_B6F7494ED173940B ON question (recommendation_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_QUESTION_SCENARIO_CODE ON question (scenario_id, code)');
        $this->addSql('CREATE TABLE recommendation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, titre VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, offres JSON NOT NULL, aides JSON NOT NULL, cta_label VARCHAR(120) DEFAULT NULL, cta_url VARCHAR(255) DEFAULT NULL, scenario_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_433224D2E04E49DF ON recommendation (scenario_id)');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A251E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A25E349CFC0 FOREIGN KEY (question_suivante_id) REFERENCES question (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A25D173940B FOREIGN KEY (recommendation_id) REFERENCES recommendation (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_scenario ADD CONSTRAINT FK_78A92108A0520E1C FOREIGN KEY (question_initiale_id) REFERENCES question (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494EE04E49DF FOREIGN KEY (scenario_id) REFERENCES event_scenario (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494EE349CFC0 FOREIGN KEY (question_suivante_id) REFERENCES question (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494ED173940B FOREIGN KEY (recommendation_id) REFERENCES recommendation (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recommendation ADD CONSTRAINT FK_433224D2E04E49DF FOREIGN KEY (scenario_id) REFERENCES event_scenario (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE answer DROP CONSTRAINT FK_DADD4A251E27F6BF');
        $this->addSql('ALTER TABLE answer DROP CONSTRAINT FK_DADD4A25E349CFC0');
        $this->addSql('ALTER TABLE answer DROP CONSTRAINT FK_DADD4A25D173940B');
        $this->addSql('ALTER TABLE event_scenario DROP CONSTRAINT FK_78A92108A0520E1C');
        $this->addSql('ALTER TABLE question DROP CONSTRAINT FK_B6F7494EE04E49DF');
        $this->addSql('ALTER TABLE question DROP CONSTRAINT FK_B6F7494EE349CFC0');
        $this->addSql('ALTER TABLE question DROP CONSTRAINT FK_B6F7494ED173940B');
        $this->addSql('ALTER TABLE recommendation DROP CONSTRAINT FK_433224D2E04E49DF');
        $this->addSql('DROP TABLE answer');
        $this->addSql('DROP TABLE event_scenario');
        $this->addSql('DROP TABLE question');
        $this->addSql('DROP TABLE recommendation');
    }
}
