<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260616132939 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Vérification d éligibilité : table eligibility_check + colonne recommendation.verification.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE eligibility_check (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, aide_code VARCHAR(64) NOT NULL, methode VARCHAR(16) NOT NULL, statut VARCHAR(16) NOT NULL, source VARCHAR(120) DEFAULT NULL, document_nom VARCHAR(255) DEFAULT NULL, donnees JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_688D136A76ED395 ON eligibility_check (user_id)');
        $this->addSql('ALTER TABLE eligibility_check ADD CONSTRAINT FK_688D136A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recommendation ADD verification JSON DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE eligibility_check DROP CONSTRAINT FK_688D136A76ED395');
        $this->addSql('DROP TABLE eligibility_check');
        $this->addSql('ALTER TABLE recommendation DROP verification');
    }
}
