<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260617145000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        // Drop payment FK on forfait BEFORE dropping forfait table
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT fk_payment_forfait');
        $this->addSql('DROP INDEX idx_payment_forfait');
        $this->addSql('ALTER TABLE forfait DROP CONSTRAINT fk_forfait_user');
        $this->addSql('DROP TABLE forfait');
        $this->addSql('ALTER TABLE abonnement ADD renewal_notified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('DROP INDEX IF EXISTS idx_contract_status');
        $this->addSql('ALTER TABLE contract ADD payeur_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE contract DROP payer_name');
        $this->addSql('ALTER TABLE contract DROP payer_email');
        $this->addSql('ALTER TABLE contract ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE contract ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              contract
            ADD
              CONSTRAINT FK_E98F2859422667C5 FOREIGN KEY (payeur_id) REFERENCES payeur (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql('CREATE INDEX IDX_E98F2859422667C5 ON contract (payeur_id)');
        $this->addSql('ALTER INDEX idx_contract_user RENAME TO IDX_E98F2859A76ED395');
        $this->addSql('ALTER INDEX idx_journey_user RENAME TO IDX_C816C6A2A76ED395');
        $this->addSql('ALTER TABLE line_subscription ALTER notified_disruption_ids DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_e8d2a1d0a76ed395 RENAME TO IDX_9AF2B191A76ED395');
        $this->addSql('ALTER INDEX idx_e8d2a1d071baa4a1 RENAME TO IDX_9AF2B1914D7B7542');
        $this->addSql('ALTER TABLE payment RENAME COLUMN forfait_id TO abonnement_id');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              payment
            ADD
              CONSTRAINT FK_6D28840DF1D74413 FOREIGN KEY (abonnement_id) REFERENCES abonnement (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql('CREATE INDEX IDX_6D28840DF1D74413 ON payment (abonnement_id)');
        $this->addSql('ALTER INDEX idx_payment_user RENAME TO IDX_6D28840DA76ED395');
        $this->addSql('DROP INDEX idx_dossier_status');
        $this->addSql('ALTER TABLE subscription_dossier ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE subscription_dossier ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_dossier_user RENAME TO IDX_4E5D00ACA76ED395');
        $this->addSql('ALTER INDEX idx_c7a0a3a5a76ed395 RENAME TO IDX_B13544D4A76ED395');
        $this->addSql('ALTER INDEX idx_d175cd9598d2c56a RENAME TO IDX_B8838839AC0396');
        $this->addSql('ALTER INDEX idx_8d93d649a76ed395 RENAME TO IDX_3F980AC8A76ED395');
        $this->addSql('ALTER INDEX idx_8d93d64971baa4a1 RENAME TO IDX_3F980AC84D7B7542');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE forfait (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              user_id INT NOT NULL,
              label VARCHAR(80) NOT NULL,
              price NUMERIC(8, 2) NOT NULL,
              expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              renewal_notified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_forfait_user ON forfait (user_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              forfait
            ADD
              CONSTRAINT fk_forfait_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql('ALTER TABLE abonnement DROP renewal_notified_at');
        $this->addSql('ALTER TABLE contract DROP CONSTRAINT FK_E98F2859422667C5');
        $this->addSql('DROP INDEX IDX_E98F2859422667C5');
        $this->addSql('ALTER TABLE contract ADD payer_name VARCHAR(180) DEFAULT NULL');
        $this->addSql('ALTER TABLE contract ADD payer_email VARCHAR(180) DEFAULT NULL');
        $this->addSql('ALTER TABLE contract DROP payeur_id');
        $this->addSql('ALTER TABLE contract ALTER id SET DEFAULT nextval(\'contract_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE contract ALTER id DROP IDENTITY');
        $this->addSql('CREATE INDEX idx_contract_status ON contract (status)');
        $this->addSql('ALTER INDEX idx_e98f2859a76ed395 RENAME TO idx_contract_user');
        $this->addSql('ALTER INDEX idx_c816c6a2a76ed395 RENAME TO idx_journey_user');
        $this->addSql('ALTER TABLE line_subscription ALTER notified_disruption_ids SET DEFAULT \'[]\'');
        $this->addSql('ALTER INDEX idx_9af2b1914d7b7542 RENAME TO idx_e8d2a1d071baa4a1');
        $this->addSql('ALTER INDEX idx_9af2b191a76ed395 RENAME TO idx_e8d2a1d0a76ed395');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840DF1D74413');
        $this->addSql('DROP INDEX IDX_6D28840DF1D74413');
        $this->addSql('ALTER TABLE payment RENAME COLUMN abonnement_id TO forfait_id');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              payment
            ADD
              CONSTRAINT fk_payment_forfait FOREIGN KEY (forfait_id) REFERENCES forfait (id) ON DELETE
            SET
              NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql('CREATE INDEX idx_payment_forfait ON payment (forfait_id)');
        $this->addSql('ALTER INDEX idx_6d28840da76ed395 RENAME TO idx_payment_user');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              subscription_dossier ALTER id
            SET
              DEFAULT nextval(
                'subscription_dossier_id_seq' :: regclass
              )
        SQL);
        $this->addSql('ALTER TABLE subscription_dossier ALTER id DROP IDENTITY');
        $this->addSql('CREATE INDEX idx_dossier_status ON subscription_dossier (status)');
        $this->addSql('ALTER INDEX idx_4e5d00aca76ed395 RENAME TO idx_dossier_user');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              support_account_request ALTER id
            SET
              DEFAULT nextval(
                'support_account_request_id_seq' :: regclass
              )
        SQL);
        $this->addSql('ALTER TABLE support_account_request ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_b13544d4a76ed395 RENAME TO idx_c7a0a3a5a76ed395');
        $this->addSql('ALTER INDEX idx_b8838839ac0396 RENAME TO idx_d175cd9598d2c56a');
        $this->addSql('ALTER INDEX idx_3f980ac84d7b7542 RENAME TO idx_8d93d64971baa4a1');
        $this->addSql('ALTER INDEX idx_3f980ac8a76ed395 RENAME TO idx_8d93d649a76ed395');
    }
}
